Repository SKY-HORSE-MAN-POWER/BE_Members, pull requests merged in 2024-05, with the labels that each got.

#9 Feature/#3,#4
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberService.java
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/domain/Member.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberCareerAddRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberCareerDeleteRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberQualificationAddRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberQualificationDeleteRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberSaveCareerRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberUpdateRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/infrastructure/CareerRepository.java
  src/main/java/com/leeforgiveness/memberservice/auth/infrastructure/QualificationRepository.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/MemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberCareerAddRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberCareerDeleteRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberQualificationAddRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberQualificationDeleteRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberSaveCareerRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberUpdateRequestVo.java
Labels: enhancement

#11 Refactor/#10
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/MemberController.java
  src/main/java/com/leeforgiveness/memberservice/common/BaseTimeEntity.java
  src/main/java/com/leeforgiveness/memberservice/common/CommonResponse.java
  src/main/java/com/leeforgiveness/memberservice/common/SuccessResponse.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/BaseException.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/BaseResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ExceptionResponse.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: enhancement

#12 Feature/#6
  build.gradle
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberService.java
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberSnsLoginRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/MemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberSnsLoginRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/common/CommonResponse.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/common/security/ApplicationConfig.java
  src/main/java/com/leeforgiveness/memberservice/common/security/FailedException.java
  src/main/java/com/leeforgiveness/memberservice/common/security/JwtAuthenticationFilter.java
  src/main/java/com/leeforgiveness/memberservice/common/security/JwtTokenProvider.java
  src/main/java/com/leeforgiveness/memberservice/common/security/SecurityConfiguration.java
Labels: enhancement

#20 Refactor/#17
  build.gradle
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/CustomException.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/GlobalExceptionHandler.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/common/security/ApplicationConfig.java
  src/main/java/com/leeforgiveness/memberservice/common/security/FailedException.java
Labels: enhancement

#47 refactor:authorization컨트롤러 non-authorization 컨트롤러 분리(#46)
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/AuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/MemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/NonAuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/sms/presentation/SmsController.java
Labels: enhancement

#50 [DEPLOYMENT] API 배포
  .gitignore
  build.gradle
  src/main/java/com/leeforgiveness/memberservice/MemberserviceApplication.java
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/infrastructure/MemberRepository.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/AuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/MemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/NonAuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/common/BaseTimeEntity.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/common/security/JwtTokenProvider.java
  src/main/java/com/leeforgiveness/memberservice/config/JpaConfig.java
  src/main/java/com/leeforgiveness/memberservice/sms/application/SmsServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/sms/presentation/SmsController.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionService.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionService.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/domain/AuctionSubscription.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/domain/SellerSubscription.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/AuctionSubscribeRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SellerSubscribeRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedAuctionsRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedAuctionsResponseDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedSellersRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedSellersResponseDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/infrastructure/AuctionSubscriptionRepository.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/infrastructure/SellerSubscriptionRepository.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/AuctionSubscriptionController.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/SellerSubscribeController.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/state/PageState.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/state/SubscribeState.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/AuctionSubscribeRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/SellerSubscribeRequestVo.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/SubscribedAuctionsResponseVo.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/SubscribedSellersResponseVo.java
  src/test/java/com/leeforgiveness/memberservice/common/GenerateRandom.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/auction/AuctionSubscribeTest.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/seller/SellerSubscribeTest.java
Labels: deployment

#64 Feature/#58
  .gitignore
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberService.java
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/infrastructure/MemberRepository.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/sms/application/SmsServiceImpl.java
Labels: enhancement

#67 Hotfix/#34
  .github/workflows/gradle.yml
  src/main/resources/application.yml
Labels: deployment

#76 [DEPLOYMENT] swagger 수정사항 배포
  src/main/java/com/leeforgiveness/memberservice/common/swagger/SwaggerConfig.java
Labels: deployment

#78 refactor: server url 수정
  src/main/java/com/leeforgiveness/memberservice/common/swagger/SwaggerConfig.java
Labels: bug

#79 [DEPLOYMENT] swagger server url 수정
  src/main/java/com/leeforgiveness/memberservice/common/swagger/SwaggerConfig.java
Labels: deployment

#81 Refactor/#80
  .github/workflows/gradle.yml
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionServiceImpl.java
Labels: enhancement

#82 [DEPLOYMENT] API 수정사항 배포
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionServiceImpl.java
Labels: deployment

#87 [DEPLOYMENT] 수정사항 배포
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: deployment

#89 refactor:ResponseStatus에 중간에 ;있어서 에러나는거 해결
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: bug

#90 [DEPLOYMENT] 빌드에러 수정 배포
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: bug

#92 [DEPLOYMENT] 수정사항 배포
  src/main/java/com/leeforgiveness/memberservice/sms/presentation/SmsController.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/auction/AuctionSubscribeTest.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/seller/SellerSubscribeTest.java
Labels: deployment

#95 [DEPLOYMENT] github action 수정사항 반영
  .github/workflows/gradle.yml
Labels: deployment

#99 [Development] 수정사항 적용 #96
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/SnsMemberAddRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/NonAuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/SnsMemberAddRequestVo.java
Labels: deployment

#101 refactor:USERNOTFOUND 오류코드 수정(#100)
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: enhancement

#102 [Deployment] usernotfound오류코드 수정
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
Labels: deployment

#106 Feature/#84
  build.gradle
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/message/AuctionSubscriptionMessage.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/message/SellerSubscriptionMessage.java
Labels: enhancement

#108 feat: 핸들로 멤버 uuid 뽑아오는 api 완성(#107)
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberService.java
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/auth/dto/MemberUuidResponseDto.java
  src/main/java/com/leeforgiveness/memberservice/auth/presentation/NonAuthorizationMemberController.java
  src/main/java/com/leeforgiveness/memberservice/auth/vo/MemberUuidResponseVo.java
Labels: enhancement

#113 refator: 회원정보 수정시에 핸들을 원래랑 같은 값을 입력하면 이미 있는 핸들이라고 뜨는 문제 해결
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
Labels: enhancement

#114 [REFACTOR] 회원정보 수정시에 핸들이 문제가 있었던거 해결
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
Labels: enhancement

#117 Refactor/#116
  src/main/java/com/leeforgiveness/memberservice/auth/application/MemberServiceImpl.java
Labels: enhancement

#124 Feature/#122
  build.gradle
  src/main/resources/logback-spring.xml
Labels: enhancement

#125 [DEPLOYMENT] kafka & ELK 설정 배포
  build.gradle
  src/main/resources/logback-spring.xml
Labels: deployment

#129 feat: 경매글 구독 여부 조회 API 구현
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionService.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/AuctionSubscriptionController.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/IsSubscribedResponseVo.java
Labels: enhancement

#130 [DEPOLYMENT] 경매글 구독 여부 조회 API 배포
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionService.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/AuctionSubscriptionController.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/vo/IsSubscribedResponseVo.java
Labels: deployment

#132 [DEPLOYMENT] 수정된 구독 API 배포
  src/main/java/com/leeforgiveness/memberservice/common/exception/ResponseStatus.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/SellerSubscriptionServiceImpl.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedAuctionsRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/dto/SubscribedSellersRequestDto.java
  src/main/java/com/leeforgiveness/memberservice/subscribe/state/PageState.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/auction/AuctionSubscribeTest.java
  src/test/java/com/leeforgiveness/memberservice/subscribe/seller/SellerSubscribeTest.java
Labels: deployment

#135 [DEPLOYMENT] 경매글 구독 여부 조회 예외처리 배포
  src/main/java/com/leeforgiveness/memberservice/subscribe/application/AuctionSubscriptionServiceImpl.java
Labels: deployment
